language: python
dist: bionic

jobs:
  fast_finish: true
  include:
    - python: '3.6'
    - python: '3.7'
    - python: '3.8'
    - python: '3.9-dev'
    - python: nightly

script:
    - python -VV
    - python runtests.py --current --verbose
